#
# network_mode: host — mesmo que VPS / scripts Windows (127.0.0.1).
#

gameserver.network.client.port = 7780
gameserver.network.client.host = *
gameserver.network.client.maxplayers = 100

gameserver.network.login.address = 127.0.0.1:9016
gameserver.network.login.gsid = 1
gameserver.network.login.password = aion

gameserver.network.chat.address = 127.0.0.1:9021
gameserver.network.chat.password = aion_chat

gameserver.network.nio.threads = 1
gameserver.network.packet.processor.threads.min = 4
gameserver.network.packet.processor.threads.max = 4
gameserver.network.packet.processor.threshold.kill = 3
gameserver.network.packet.processor.threshold.spawn = 50
gameserver.network.display.unknownpackets = false
gameserver.network.flood.connections = false
gameserver.network.flood.tick = 1000
gameserver.network.flood.short.warn = 10
gameserver.network.flood.short.reject = 20
gameserver.network.flood.short.tick = 10
gameserver.network.flood.long.warn = 30
gameserver.network.flood.long.reject = 60
gameserver.network.flood.long.tick = 60
